version: "3.9"
services:
  web:
    ports:
      - "5000:80"
    image: "manfish88/apps-ivan"
    volumes:
      - vol-data:/var/www/html/assets
  web2:
    ports:
      - "5001:80"
    image: "nginx"
  web3:
    ports:
      - "5002:80"
    image: "ubuntu/apache2"
volumes:
  vol-data: